// Code generated by MockGen. DO NOT EDIT.
// Source: internal/webhook/webhook.go

// Package webhookmocks is a generated GoMock package.
package webhookmocks

import (
	reflect "reflect"
	webhook "test_auth/internal/webhook"

	gomock "github.com/golang/mock/gomock"
)

// MockWebhook is a mock of Webhook interface.
type MockWebhook struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookMockRecorder
}

// MockWebhookMockRecorder is the mock recorder for MockWebhook.
type MockWebhookMockRecorder struct {
	mock *MockWebhook
}

// NewMockWebhook creates a new mock instance.
func NewMockWebhook(ctrl *gomock.Controller) *MockWebhook {
	mock := &MockWebhook{ctrl: ctrl}
	mock.recorder = &MockWebhookMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhook) EXPECT() *MockWebhookMockRecorder {
	return m.recorder
}

// Request mocks base method.
func (m *MockWebhook) Request(v webhook.Body) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Request indicates an expected call of Request.
func (mr *MockWebhookMockRecorder) Request(v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockWebhook)(nil).Request), v)
}
