// Code generated by MockGen. DO NOT EDIT.
// Source: internal/token/token.go

// Package tokenmocks is a generated GoMock package.
package tokenmocks

import (
	reflect "reflect"

	jwt "github.com/golang-jwt/jwt/v5"
	gomock "github.com/golang/mock/gomock"
)

// MockToken is a mock of Token interface.
type MockToken struct {
	ctrl     *gomock.Controller
	recorder *MockTokenMockRecorder
}

// MockTokenMockRecorder is the mock recorder for MockToken.
type MockTokenMockRecorder struct {
	mock *MockToken
}

// NewMockToken creates a new mock instance.
func NewMockToken(ctrl *gomock.Controller) *MockToken {
	mock := &MockToken{ctrl: ctrl}
	mock.recorder = &MockTokenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToken) EXPECT() *MockTokenMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockToken) Create(claims jwt.Claims) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", claims)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTokenMockRecorder) Create(claims interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockToken)(nil).Create), claims)
}

// CreateJTI mocks base method.
func (m *MockToken) CreateJTI() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJTI")
	ret0, _ := ret[0].(string)
	return ret0
}

// CreateJTI indicates an expected call of CreateJTI.
func (mr *MockTokenMockRecorder) CreateJTI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJTI", reflect.TypeOf((*MockToken)(nil).CreateJTI))
}

// CreateRefresh mocks base method.
func (m *MockToken) CreateRefresh() (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefresh")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateRefresh indicates an expected call of CreateRefresh.
func (mr *MockTokenMockRecorder) CreateRefresh() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefresh", reflect.TypeOf((*MockToken)(nil).CreateRefresh))
}

// Parse mocks base method.
func (m *MockToken) Parse(token string, claims jwt.Claims) (jwt.Claims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", token, claims)
	ret0, _ := ret[0].(jwt.Claims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockTokenMockRecorder) Parse(token, claims interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockToken)(nil).Parse), token, claims)
}

// ValidateRefresh mocks base method.
func (m *MockToken) ValidateRefresh(hashed, refresh string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateRefresh", hashed, refresh)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ValidateRefresh indicates an expected call of ValidateRefresh.
func (mr *MockTokenMockRecorder) ValidateRefresh(hashed, refresh interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateRefresh", reflect.TypeOf((*MockToken)(nil).ValidateRefresh), hashed, refresh)
}
